baseURL = 'https://sanfranciscoave.com/'
languageCode = 'en-us'
title = 'Francisco'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Now"
url = "/Now"
weight = 3

[[menu.main]]
name = "About"
url = "/About"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5
